# Generated by Django 6.0.4 on 2026-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_approach_experience_profile_skill_sociallink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', '-proficiency', 'name']},
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Languages'), ('programming', 'Programming Languages'), ('technology', 'Technology'), ('non_technical', 'Non-Technical')], max_length=20),
        ),
    ]
