# Generated by Django 6.0.4 on 2026-05-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_skill_options_skill_proficiency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('certificate_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Course & Training',
                'verbose_name_plural': 'Courses & Trainings',
                'ordering': ['-date'],
            },
        ),
    ]
