# Generated by Django 6.0.4 on 2026-05-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coursetraining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetraining',
            name='certificate_url',
        ),
        migrations.AddField(
            model_name='coursetraining',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
